### ISSUE TITLE
CD for binary build deployment

### ISSUE THREAD

**Issue by TimothyStiles** [JacobBumgarner/VesselVio#32]
The install instructions include a [link](https://jacobbumgarner.github.io/VesselVio/Downloads.html) to download executable binaries for both MacOSX and Windows but I can't find these binaries as part of Vessel's latest [Github release](https://github.com/JacobBumgarner/VesselVio/releases/tag/v1.1.1). Instead there are only links to sourceforge. On each release they should be automatically built and pushed to a github release then deployed to each systems' respective package manager (homebrew, apt-get, choco, etc).

I used to do this when I was shipping a CLI with one of my projects using [GoReleaser](https://github.com/goreleaser/goreleaser). It's Go specific but the idea is the same. GoReleaser builds and deploys to almost every modern architecture/OS/package manager under the sun. Maybe there's a python equivalent?

**Comment by JacobBumgarner** [comment]
This is a great suggestion and honestly one of the things that I've been lagging with at the moment - keeping the app up to date with the GitHub releases.

To make sure I'm understanding correctly, basically anytime I push a version release, I would have a GitHub Action that would bundle the app for each OS and then send that bundle to SourceForge/etc. into an updated version folder?

It would be extremely useful if I could find something equivalent to this - I'm sure it has to exist...

**Comment by TimothyStiles** [comment]
> This is a great suggestion and honestly one of the things that I've been lagging with at the moment - keeping the app up to date with the GitHub releases.
> 
> To make sure I'm understanding correctly, basically anytime I push a version release, I would have a GitHub Action that would bundle the app for each OS and then send that bundle to SourceForge/etc. into an updated version folder?
> 
> It would be extremely useful if I could find something equivalent to this - I'm sure it has to exist...

Exactly but you can just host each app bundle on the GitHub release page instead of using sourceforge.

**Comment by JacobBumgarner** [comment]
> Exactly but you can just host each app bundle on the GitHub release page instead of using sourceforge

Hmmm, I didn't think GitHub allowed you to host files larger than 25 mb, though?

**Comment by JacobBumgarner** [comment]
Jk- please ignore that. Didn't realize that there was a different file limit for GitHub Releases. This seems like a great solution :)
