### ISSUE TITLE
Create code coverage badge.

### ISSUE THREAD

**Issue by TimothyStiles** [JacobBumgarner/VesselVio#33]
At the top of VesselVio's README there should be a code coverage badge like this: ![Test Coverage](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/TimothyStiles/e58f265655ac0acacdd1a38376ccd32a/raw/coverage.json)

There are third party services such as coveralls, or[ code cov](https://about.codecov.io/), that will generate these badges for you.

I roll my own using [github actions](https://github.com/TimothyStiles/poly/blob/prime/.github/workflows/coverage.yml) and [github gists for data storage](https://gist.github.com/TimothyStiles/e58f265655ac0acacdd1a38376ccd32a) which gets rendered as a badge via [shields.io](https://shields.io/)
![Screen Shot 2022-05-16 at 5 01 39 PM](https://user-images.githubusercontent.com/7042260/168701184-fc5ba334-cf17-4141-9dc0-d42be7c1c5a8.png)
 
These goofy little badges do a lot to assure other developers that they can trust your code to work as anticipated and help attract more users and contributors.

**Comment by JacobBumgarner** [comment]
Just started working on getting unit tests integrated today, actually :) I 

I've seen some packages use CodeCov, but I haven't figured out how to get that integrated yet. I like your approach too!
