### ISSUE TITLE
Create test backed tutorial

### ISSUE THREAD

**Issue by TimothyStiles** [JacobBumgarner/VesselVio#34]
Go has this really great built-in language feature called an [example test](https://go.dev/blog/examples)

Basic idea is that you write your tutorials as tests that get rendered to your doc site on release. These help increase code coverage but more importantly will never let you release builds with out of date docs. Your CI/CD process will instead yell at you to fix it before you can release it.

I personally find tracking what needs to be updated in my docs impossible without this feature. Someone mentioned to me that there's a third-party thing in Python that does this and if there is such a thing I'd highly recommend it.

**Comment by JacobBumgarner** [comment]
Going to merge this into #31, which will encompass unit testing. Thanks @TimothyStiles !
