### ISSUE TITLE
[Feature Request]: Option to export the skeleton as an image

### ISSUE THREAD

**Issue by saskra** [JacobBumgarner/VesselVio#52]
### Describe the feature you would like to be added.

As the title says, it would be handy for me to be able to export the skeleton as an image so I could visually compare it to the segmentation and results of other skeletonization algorithms. Alternatively, I would appreciate tips on if and how I can convert the GraphML file back to a skeleton and save it as an image.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

PS: Did you actually change anything besides the speed on the Lee94 skeleton algorithm? Despite the same segmentation and skeletonization (Lee94 using scikit), I got different results with other software. Or is that due to post-processing?

**Comment by JacobBumgarner** [comment]
Hi @saskra , I have had extremely minimal time to maintain the app, so I don't think I'm going to add this feature. If you are interested in creating a PR for the feature, I'd be happy to check it over.

As far as your other question, I implemented algorithm as it was described in the original Lee94 paper. It does produce minimally different skeletons than the scikit algorithm for one reason:
The direction of the scans are different. This minimally affects the final shape of the skeleton, but I didn't observe significant differences between mine & the scikit learn skeleton voxel counts. If you observe other implementations of this algorithm that float around (many in MATLAB), you will notice similar minor differences.

**Comment by saskra** [comment]
Thanks for your answer! In fact, after a change of job, I no longer work on this topic, so there is no longer a need from my side.
