### ISSUE TITLE
[Bug]:  fdopen() failed unexpectedly

### ISSUE THREAD

**Issue by saskra** [JacobBumgarner/VesselVio#53]
### What happened?

"VesselVio.py" reproducibly crashes on our Windows 10 workstation after 170 files (about 1 hour runtime) with the following error message:

```shell
(VesselVio) C:\Users\Vessels-Project\VesselVio>python VesselVio.py
Traceback (most recent call last):
  File "C:\Users\Vessels-Project\VesselVio\library\qt_threading.py", line 263, in run
    GIO.save_cache(filename, gen_options.results_folder)
  File "C:\Users\Vessels-Project\VesselVio\library\graph_io.py", line 303, in save_cache
    g.write(file)
  File "C:\Users\Vessels-Project\anaconda3\envs\VesselVio\lib\site-packages\igraph\__init__.py", line 2988, in write
    return writer(f, *args, **kwds)
RuntimeError: fdopen() failed unexpectedly
```

This is done both with the downloaded .exe and with the current source code in a separate conda environment. The environment is composed as follows:
[environment_windows.txt](https://github.com/JacobBumgarner/VesselVio/files/9104483/environment_windows.txt)

### Operating System

Windows

### App Build

Downloaded App

### Pseudocode or Screenshots

```python 
 Insert code here 
 ```
 Or drag your screenshot here! 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JacobBumgarner** [comment]
Hi @saskra 

Sorry to hear about this crash. The error report you provided is on `igraph`'s  end. But that doesn't mean that there isn't some issue with the graph that VesselVio is providing to the `igraph` writer.

My first hunch is that the 170th graph file that's being loaded into the app for analysis is what's causing the problem.

Would you be able to try to identify the file that is being saved when the app is crashing and try to analyze that one by itself?

My second hunch is that there may be some issue with a memory leak in the app. 

Maybe we can try to figure which file might be causing the issue before I start digging into memory issues.

**Comment by JacobBumgarner** [comment]
I will also inform you that the app caches the results from each dataset after it's analyzed, so the analysis results from the first 170 files are present in the result cache. If you analyze a single file, that cache will be emptied and saved into an excel file.

**Comment by JacobBumgarner** [comment]
Hmm - ok thanks for that update.

Can you describe more about the files you're analyzing and the exact settings that your using during the analysis?
