### ISSUE TITLE
[Bug]: No such file or no access: 'VOLUME_FILE.nii'

### ISSUE THREAD

**Issue by Kingxudong** [JacobBumgarner/VesselVio#64]
### What happened?

  File "e:\VesselVio-main\VVTerminal.py", line 158, in process_volume
    volume, image_shape = ImProc.load_volume(volume_file, verbose=verbose)
TypeError: cannot unpack non-iterable NoneType object
vtkDebugLeaks has found no leaks.

When I ran the project, I found this problem, and this data was not available. Also, when I used the software to visualize the voxels, I found that the original blood vessels had already been smoothed and processed at the time of input. But the corresponding module is not found in the project. Where is it?

### Operating System

Windows

### App Build

Manual app build (pyenv, conda, etc)

### Pseudocode or Screenshots

```python 
 Insert code here 
 ```
 Or drag your screenshot here!

**Comment by JacobBumgarner** [comment]
Hi @Kingxudong 

That `VOLUME_FILE.nii` is meant to be an indicator that you should paste in the path to your volume file at that position.
